### ISSUE TITLE
Feature/Cant purchase more than once.

### ISSUE THREAD

**Issue by amshelhack3r** [KingSonkorey69/website#11]
Before you do a transaction to purchase. check if the user has already bought the book. 
If the user user has bought it already return with a message "book already bought"
Create a method in Crud class called checkPurchasedBook($bookId) 
Inside the method you query the invoice table to check if the bookID and user return a record.
Call the above method in mrequest.php after line 33. 
Do an if else to check if the method returned any rows. if it did we dont request for mpesa. if not we continue with mpesa

**Comment by amshelhack3r** [comment]
Awaiting review

**Comment by KingSonkorey69** [comment]
the method is working
