### ISSUE TITLE
Cpanel Git

### ISSUE THREAD

**Issue by amshelhack3r** [KingSonkorey69/website#18]
In the Cpanel git, I noticed you have quite a few branches.
This should not be the case. You should only have 2branches. Master and develop.
If you are working on another branch locally then update on Github
<img width="1792" alt="Screenshot 2021-07-09 at 15 14 42" src="https://user-images.githubusercontent.com/33036027/125076494-a7e7cf00-e0c8-11eb-9fba-98f1c9c6937d.png">
 you should create a pull request so it can be merged to either develop or master

**Comment by KingSonkorey69** [comment]
already done that
